# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141a7f563d0a7f6007a53677381664b8431dd31d8163fabb49bbd5839f08a17e5e524d69b5e570731d5f200233b27f2a2801559a8d1e53e6de73765c97e7a12f

test:
  secret_key_base: ebfc6434ff05c2706fe2c88f0dab94abcb3010f2d22957b3e64c04a10eadb3780e3d4c64065513fae8dde05df660d60eb690b9c514125aa3e16b6882c9f0bf08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
